service: diabetes_prediction_final
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2


package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - .idea/**
    - node_module/**

functions:
  hello:
    handler: handler.predict
    memorySize: 512
    timeout: 25
    events:
      - http:
          path: predict-diabetes
          method: get
          request:
            parameters:
              queryString:
                Pregnancies: true
                glucose: true
                BP: true
                SkinThickness: true
                Insulin: true
                BMI: true
                DiabetesPedigreeFunction: true
                Age: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true













