service: diabetes-prediction

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sagemaker:InvokeEndpoint
      Resource: "arn:aws:sagemaker:us-west-2:349085393863:endpoint/diabetes-prediction"
  environment:
    SAGEMAKER_ENDPOINT_NAME: "diabetes-prediction"

functions:
  hello:
    handler: handler.detectDiabetes
    events:
      - http:
          path: sagemaker
          method: post
          cors: true
